[package]
name = "type_analysis"
version = "2.1.0"
authors = ["Costa Group UCM","iden3"]
edition = "2018"

[dependencies]
program_structure = {path = "../program_structure"}
num-bigint-dig = "0.6.0"
num-traits = "0.2.6"
