[package]
name = "code_producers"
version = "2.1.0"
authors = ["Costa Group UCM","iden3"]
edition = "2018"

[dependencies]
handlebars = "4.1.3"
lz_fnv = "0.1.2"
num-bigint-dig = "0.6.0"
serde_json = "1.0.68"
