[package]
name = "code_producers"
version = "2.2.2"
authors = ["Costa Group UCM","iden3"]
edition = "2018"

[dependencies]
circom_algebra = { path = "../circom_algebra" }
handlebars = "4.1.3"
lz_fnv = "0.1.2"
num-bigint-dig = "0.8.4"
serde_json = "1.0.68"
